// <auto-generated />
using System;
using DomainCopilot.Infrastructure.Ingestion.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DomainCopilot.Infrastructure.Migrations
{
    [DbContext(typeof(DomainCopilotDbContext))]
    [Migration("20260902112832_AddTokenBudgetAndUsageRecordTables")]
    partial class AddTokenBudgetAndUsageRecordTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainCopilot.Domain.Entities.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicalCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("AgentRuns", (string)null);
                });

            modelBuilder.Entity("DomainCopilot.Domain.Entities.AgentStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Output")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StepIndex")
                        .HasColumnType("int");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StepIndex")
                        .IsUnique();

                    b.ToTable("AgentSteps", (string)null);
                });

            modelBuilder.Entity("DomainCopilot.Domain.Entities.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicianUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EditedContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalDraftContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("ApprovalDecisions", (string)null);
                });

            modelBuilder.Entity("DomainCopilot.Domain.Entities.TokenBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AllocatedTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("ConsumedTokens")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PeriodStart", "PeriodEnd");

                    b.ToTable("TokenBudgets", (string)null);
                });

            modelBuilder.Entity("DomainCopilot.Domain.Entities.UsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("UserId", "RecordedAt");

                    b.ToTable("UsageRecords", (string)null);
                });

            modelBuilder.Entity("DomainCopilot.Domain.Ingestion.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("int");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("GuidelineEffectiveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GuidelineVersionLabel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .IsUnique();

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("DomainCopilot.Domain.Ingestion.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentVersion")
                        .HasColumnType("int");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentId", "DocumentVersion");

                    b.ToTable("DocumentChunks", (string)null);
                });

            modelBuilder.Entity("DomainCopilot.Infrastructure.Orchestration.ApprovalAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicianUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("ApprovalAudits", (string)null);
                });

            modelBuilder.Entity("DomainCopilot.Infrastructure.Safety.DrugInteractionRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DrugANormalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DrugBNormalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DrugANormalized", "DrugBNormalized")
                        .IsUnique();

                    b.ToTable("DrugInteractionRules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "ACE inhibitor + potassium-sparing diuretic combination carries a hyperkalemia risk; recommend potassium monitoring, especially at reduced renal function.",
                            DrugANormalized = "lisinopril",
                            DrugBNormalized = "spironolactone",
                            RuleId = "RULE_ACEI_KSPARING_HYPERKALEMIA",
                            Severity = "Caution"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fluoroquinolone antibiotics are among the drug classes that can increase bleeding risk in patients on warfarin; recommend closer INR monitoring than the routine schedule.",
                            DrugANormalized = "warfarin",
                            DrugBNormalized = "ciprofloxacin",
                            RuleId = "RULE_FLUOROQUINOLONE_WARFARIN_BLEEDING",
                            Severity = "Caution"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fluoroquinolone antibiotics are among the drug classes that can increase bleeding risk in patients on warfarin; recommend closer INR monitoring than the routine schedule.",
                            DrugANormalized = "warfarin",
                            DrugBNormalized = "levofloxacin",
                            RuleId = "RULE_FLUOROQUINOLONE_WARFARIN_BLEEDING",
                            Severity = "Caution"
                        });
                });

            modelBuilder.Entity("DomainCopilot.Infrastructure.Safety.KnownMedicationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NameNormalized")
                        .IsUnique();

                    b.ToTable("KnownMedications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameNormalized = "metformin"
                        },
                        new
                        {
                            Id = 2,
                            NameNormalized = "lisinopril"
                        },
                        new
                        {
                            Id = 3,
                            NameNormalized = "spironolactone"
                        },
                        new
                        {
                            Id = 4,
                            NameNormalized = "warfarin"
                        },
                        new
                        {
                            Id = 5,
                            NameNormalized = "atorvastatin"
                        },
                        new
                        {
                            Id = 6,
                            NameNormalized = "simvastatin"
                        },
                        new
                        {
                            Id = 7,
                            NameNormalized = "amlodipine"
                        },
                        new
                        {
                            Id = 8,
                            NameNormalized = "apixaban"
                        },
                        new
                        {
                            Id = 9,
                            NameNormalized = "empagliflozin"
                        },
                        new
                        {
                            Id = 10,
                            NameNormalized = "insulin glargine"
                        },
                        new
                        {
                            Id = 11,
                            NameNormalized = "ciprofloxacin"
                        },
                        new
                        {
                            Id = 12,
                            NameNormalized = "levofloxacin"
                        },
                        new
                        {
                            Id = 13,
                            NameNormalized = "nitrofurantoin"
                        },
                        new
                        {
                            Id = 14,
                            NameNormalized = "trimethoprim-sulfamethoxazole"
                        },
                        new
                        {
                            Id = 15,
                            NameNormalized = "pioglitazone"
                        });
                });

            modelBuilder.Entity("DomainCopilot.Domain.Entities.AgentStep", b =>
                {
                    b.HasOne("DomainCopilot.Domain.Entities.AgentRun", null)
                        .WithMany("Steps")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DomainCopilot.Domain.ValueObjects.TokenUsage", "Usage", b1 =>
                        {
                            b1.Property<Guid>("AgentStepId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CompletionTokens")
                                .HasColumnType("int")
                                .HasColumnName("UsageCompletionTokens");

                            b1.Property<int>("PromptTokens")
                                .HasColumnType("int")
                                .HasColumnName("UsagePromptTokens");

                            b1.HasKey("AgentStepId");

                            b1.ToTable("AgentSteps");

                            b1.WithOwner()
                                .HasForeignKey("AgentStepId");
                        });

                    b.Navigation("Usage")
                        .IsRequired();
                });

            modelBuilder.Entity("DomainCopilot.Domain.Entities.ApprovalDecision", b =>
                {
                    b.HasOne("DomainCopilot.Domain.Entities.AgentRun", null)
                        .WithOne("Approval")
                        .HasForeignKey("DomainCopilot.Domain.Entities.ApprovalDecision", "RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DomainCopilot.Domain.Entities.UsageRecord", b =>
                {
                    b.OwnsOne("DomainCopilot.Domain.ValueObjects.TokenUsage", "Usage", b1 =>
                        {
                            b1.Property<Guid>("UsageRecordId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CompletionTokens")
                                .HasColumnType("int")
                                .HasColumnName("UsageCompletionTokens");

                            b1.Property<int>("PromptTokens")
                                .HasColumnType("int")
                                .HasColumnName("UsagePromptTokens");

                            b1.HasKey("UsageRecordId");

                            b1.ToTable("UsageRecords");

                            b1.WithOwner()
                                .HasForeignKey("UsageRecordId");
                        });

                    b.Navigation("Usage")
                        .IsRequired();
                });

            modelBuilder.Entity("DomainCopilot.Domain.Entities.AgentRun", b =>
                {
                    b.Navigation("Approval");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
